=== xianliflc/BookHub/src/schemas/remote_repo_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "name" : {
            "type": "string"
        },
        "url" : {
            "type": "string"
        },
        "resource_vendor" : {
            "type": "string",
            "enum": [
                "Github",
                "Gitlab",
                "Bitbucket",
                "Amazon S3"
            ]
        },
        "vendor_setting" : {
            "type": "object",
            "properties": {
                "branch" : {
                    "type": "string"
                },
                "repo_name" : {
                    "type": "string"
                }
            }
        },
        "description": {
            "type": "string"
        },
        "version": {
            "type": "number",
            "minimum" : 1
        },
        "maintainer": {
            "type": "string"
        },
        "tags": {
            "type": "array",
            "uniqueItems": true,
            "items" : [
                {
                    "type": "string"
                }
            ]
        },
        "resource_items": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "resource_item_name": {
                            "type": "string"
                        },
                        "author": {
                            "type": "string"
                        },
                        "resource_type": {
                            "type": "string",
                            "enum": [
                                "Book",
                                "Article",
                                "Note",
                                "Video",
                                "Other"
                            ]
                        },
                        "relative_url": {
                            "type": "string"
                        },
                        "absolute_url": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "resource_item_name"
                    ],
                    "oneOf": [
                        {
                            "required": ["relative_url"]
                        },
                        {
                            "required": ["absolute_url"]
                        }
                    ]
                }
            ]
        }
    },
    "required": [
        "name",
        "resource_vendor",
        "version",
        "resource_items",
        "url"
    ]

}

=== xianliflc/BookHub/demo/lua-tutorial.json
{
    "name": "lua-tutorial",
    "resource_vendor": "Github",
    "vendor_setting" : {
        "branch": "master",
        "repo__name": "lua-tutorial"
    },
    "url": "https://github.com/mikolajgucki/lua-tutorial",
    "resource_items": [
        {
            "resource_item_name": "Lua state",
            "author": "mikolajgucki",
            "resource_type": "Book Chapter",
            "relative_url": "00-lua-state/lua-state.md",
            "description": ""
        },
        {
            "resource_item_name": "Lua stack - the key to understanding the Lua C API",
            "author": "mikolajgucki",
            "resource_type": "Book Chapter",
            "relative_url": "01-lua-stack-key-to-understanding-c-api/lua-stack-key-to-understanding-c-api.md",
            "description": ""
        },
        {
            "resource_item_name": "Calling Lua function from C/C++",
            "author": "mikolajgucki",
            "resource_type": "Book Chapter",
            "relative_url": "02-calling-lua-function/calling-lua-function.md",
            "description": ""
        },
        {
            "resource_item_name": "Implementing a Lua library in C/C++",
            "author": "mikolajgucki",
            "resource_type": "Book Chapter",
            "relative_url": "03-implementing-lua-library-in-cpp/implementing-lua-library-in-cpp.md",
            "description": ""
        },
        {
            "resource_item_name": "Manipulating Lua tables in C/C++",
            "author": "mikolajgucki",
            "resource_type": "Book Chapter",
            "relative_url": "04-manipulating-lua-tables-in-cpp/manipluating-lua-tables-in-cpp.md",
            "description": ""
        },
        {
            "resource_item_name": "Lua metatables",
            "author": "mikolajgucki",
            "resource_type": "Book Chapter",
            "relative_url": "05-lua-metatables/lua-metatables.md",
            "description": ""
        },
        {
            "resource_item_name": "Object-oriented Lua using metatables",
            "author": "mikolajgucki",
            "resource_type": "Book Chapter",
            "relative_url": "06-oo-lua-using-metatables/oo-lua-using-metatables.md",
            "description": ""
        }
    ],
    "version": 1,
    "maintainer": "mikolajgucki",
    "tags": [
        "Tutorial",
        "Programming Language",
        "Lua"
    ],
    "description": "Lua tutorial with advanced topics."
}
